'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('tasks', [

      {
        name: 'Atividade 1',
        description: 'Design.',
        contractDate: new Date(),
        contractDocument: null,
        startDate: new Date(),
        deadline: new Date(),
        updatedDeadline: null,
        taskDomain: '5',
        isActive: true,
        taskStatus: "TO_ESTIMATE",
        customerId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        name: 'Atividade 2',
        description: 'Capture beautiful moments at a wedding.',
        contractDate: new Date(),
        contractDocument: null,
        startDate: new Date(),
        deadline: new Date(),
        updatedDeadline: null,
        taskDomain: '2',
        isActive: true,
        taskStatus: "TO_ESTIMATE",
        customerId: 2, // Assuming a customer with ID 3 exists
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Atividade 3',
        description: 'Produce a commercial for a pharmacy.',
        contractDate: new Date(),
        contractDocument: null,
        startDate: new Date(),
        deadline: new Date(),
        updatedDeadline: null,
        taskDomain: '3',
        isActive: true,
        taskStatus: "OVERDUE",
        customerId: 1, 
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Atividade 4',
        description: 'Você sabe muito bem o que me resta.',
        contractDate: new Date(),
        contractDocument: null,
        startDate: new Date(),
        deadline: new Date(),
        updatedDeadline: null,
        taskDomain: '3',
        isActive: true,
        taskStatus: "OVERDUE",
        customerId: 1, 
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Atividade 5',
        description: 'Olhar o tempo me ajuda a esperar.',
        contractDate: new Date(),
        contractDocument: null,
        startDate: new Date(),
        deadline: new Date(),
        updatedDeadline: null,
        taskDomain: '3',
        isActive: true,
        taskStatus: "OVERDUE",
        customerId: 1, 
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Atividade 6',
        description: 'Porque se você vem e não apressa.',
        contractDate: new Date(),
        contractDocument: null,
        startDate: new Date(),
        deadline: new Date(),
        updatedDeadline: null,
        taskDomain: '3',
        isActive: true,
        taskStatus: "OVERDUE",
        customerId: 1, 
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Atividade 7',
        description: 'Produce a commercial for a pharmacy.',
        contractDate: new Date(),
        contractDocument: null,
        startDate: new Date(),
        deadline: new Date(),
        updatedDeadline: null,
        taskDomain: '3',
        isActive: true,
        taskStatus: "OVERDUE",
        customerId: 1, 
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Atividade 8',
        description: 'Me sobram versos tristes pra cantar.',
        contractDate: new Date(),
        contractDocument: null,
        startDate: new Date(),
        deadline: new Date(),
        updatedDeadline: null,
        taskDomain: '3',
        isActive: true,
        taskStatus: "OVERDUE",
        customerId: 1, 
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Atividade 9',
        description: 'E eu não meço as palavras que digo.',
        contractDate: new Date(),
        contractDocument: null,
        startDate: new Date(),
        deadline: new Date(),
        updatedDeadline: null,
        taskDomain: '3',
        isActive: true,
        taskStatus: "OVERDUE",
        customerId: 1, 
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Atividade 10',
        description: 'Quando digo só o que sinto.',
        contractDate: new Date(),
        contractDocument: null,
        startDate: new Date(),
        deadline: new Date(),
        updatedDeadline: null,
        taskDomain: '3',
        isActive: true,
        taskStatus: "OVERDUE",
        customerId: 1, 
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('tasks', null, {});
  },
};
